### ISSUE TITLE
Problem with NER step

### ISSUE THREAD

**Issue by svkmdl** [InaRoesiger/conversion2conll12#1]
Hi Ina, this looks like a great tool for coref in german. However, while running your script on the entire pipeline, I get an error on the NER step as:

`	#NER ...........................
Invoked on Thu Dec 19 17:18:31 CET 2019 with arguments: -loadClassifier classifiers/hgc_175m_600.crf.ser.gz -testFile ./.././output/input.txt.ne-ready
testFile=./.././output/input.txt.ne-ready
loadClassifier=classifiers/hgc_175m_600.crf.ser.gz
Loading classifier from classifiers/hgc_175m_600.crf.ser.gz ... done [2.7 sec].
Exception in thread "main" java.lang.UnsupportedOperationException: Unknown key null
	at edu.stanford.nlp.ling.CoreLabel.parseStringKeys(CoreLabel.java:253)
	at edu.stanford.nlp.sequences.ColumnDocumentReaderAndWriter.init(ColumnDocumentReaderAndWriter.java:52)
	at edu.stanford.nlp.sequences.ColumnDocumentReaderAndWriter.init(ColumnDocumentReaderAndWriter.java:46)
	at edu.stanford.nlp.ie.AbstractSequenceClassifier.makeReaderAndWriter(AbstractSequenceClassifier.java:243)
	at edu.stanford.nlp.ie.AbstractSequenceClassifier.defaultReaderAndWriter(AbstractSequenceClassifier.java:118)
	at edu.stanford.nlp.ie.crf.CRFClassifier.main(CRFClassifier.java:3038)
....................... done`

Any idea what might be causing this?

Thanks in advance for your help!

**Comment by jweckschmied** [comment]
Hi Souvik, did you ever solve this issue? I have a somewhat related problem with the same step in the pipeline, though in my case it's complaining that the key and value arrays are not the same lengths.

**Comment by svkmdl** [comment]
> Hi Souvik, did you ever solve this issue? I have a somewhat related problem with the same step in the pipeline, though in my case it's complaining that the key and value arrays are not the same lengths.

Hey, I am sorry I forgot how exactly I resolved the issue because I used it a long time ago. But I remember that I had to reformat the output before the NER step, something about the text body format was causing the problem. Hope it gives you a direction on which step to look into.
