### ISSUE TITLE
"Argument array lengths differ" error during NER 

### ISSUE THREAD

**Issue by jweckschmied** [InaRoesiger/conversion2conll12#3]
I keep getting an error in the NER step when using the tool. I assume it's got something to do with the input format (just a plain text file) but I can't figure out what the issue is.

``` #NER ...........................                                                                                                                                                                           
Invoked on Thu Dec 17 15:10:51 CET 2020 with arguments: -loadClassifier classifiers/hgc_175m_600.crf.ser.gz -testFile ./.././output/testinput.txt.ne-ready                                                         
testFile=./.././output/testinput.txt.ne-ready                                                                                                                                                                      
loadClassifier=classifiers/hgc_175m_600.crf.ser.gz                                                                                                                                                                 
Loading classifier from classifiers/hgc_175m_600.crf.ser.gz ... done [1.5 sec].                                                                                                                                    
Error on line 1: Heute O O O O                                                                                                                                                                                     
Exception in thread "main" java.lang.UnsupportedOperationException: Argument array lengths differ: [class edu.stanford.nlp.ling.CoreAnnotations$TextAnnotation, class edu.stanford.nlp.ling.CoreAnnotations$AnswerAnnotation] vs. [Heute, O, O, O, O]                                                                                                                                                                                 
        at edu.stanford.nlp.ling.CoreLabel.initFromStrings(CoreLabel.java:263)                                                                                                                                     
        at edu.stanford.nlp.ling.CoreLabel.<init>(CoreLabel.java:150)                                                                                                                                              
        at edu.stanford.nlp.sequences.ColumnDocumentReaderAndWriter$ColumnDocParser.apply(ColumnDocumentReaderAndWriter.java:92)                                                                                   
        at edu.stanford.nlp.sequences.ColumnDocumentReaderAndWriter$ColumnDocParser.apply(ColumnDocumentReaderAndWriter.java:65)                                                                                   
        at edu.stanford.nlp.objectbank.DelimitRegExIterator.parseString(DelimitRegExIterator.java:72)                                                                                                              
        at edu.stanford.nlp.objectbank.DelimitRegExIterator.setNext(DelimitRegExIterator.java:68)                                                                                                                  
        at edu.stanford.nlp.objectbank.DelimitRegExIterator.<init>(DelimitRegExIterator.java:64)                                                                                                                   
        at edu.stanford.nlp.objectbank.DelimitRegExIterator$DelimitRegExIteratorFactory.getIterator(DelimitRegExIterator.java:129)                                                                                 
        at edu.stanford.nlp.sequences.ColumnDocumentReaderAndWriter.getIterator(ColumnDocumentReaderAndWriter.java:59)                                                                                             
        at edu.stanford.nlp.objectbank.ObjectBank$OBIterator.setNextObjectHelper(ObjectBank.java:435)                                                                                                              
        at edu.stanford.nlp.objectbank.ObjectBank$OBIterator.setNextObject(ObjectBank.java:419)                                                                                                                    
        at edu.stanford.nlp.objectbank.ObjectBank$OBIterator.<init>(ObjectBank.java:412)                                                                                                                           
        at edu.stanford.nlp.objectbank.ObjectBank.iterator(ObjectBank.java:250)                                                                                                                                    
        at edu.stanford.nlp.sequences.ObjectBankWrapper.iterator(ObjectBankWrapper.java:45)                                                                                                                        
        at edu.stanford.nlp.ie.AbstractSequenceClassifier.classifyAndWriteAnswers(AbstractSequenceClassifier.java:1193)                                                                                            
        at edu.stanford.nlp.ie.AbstractSequenceClassifier.classifyAndWriteAnswers(AbstractSequenceClassifier.java:1137)                                                                                            
        at edu.stanford.nlp.ie.AbstractSequenceClassifier.classifyAndWriteAnswers(AbstractSequenceClassifier.java:1091)                                                                                            
        at edu.stanford.nlp.ie.crf.CRFClassifier.main(CRFClassifier.java:3009)                                                                                                                                     
....................... done ```

Anybody have an idea how I would go about fixing this?

**Comment by jweckschmied** [comment]
Fixed the issue by 
replacing
`perl -ne 'chomp; print "$_ O O O O\n"' $file > ./../$OUTDIR/$filename.ne-ready` with
`perl -ne 'chomp; print "$_\tO\n"' $file > ./../$OUTDIR/$filename.ne-ready`
